export enum Category {
  Frontend = "Frontend",
  Backend = "Backend",
  Design = "Design",
  Mobile = "Mobile",
  DevOps = "DevOps",
  Web3 = "Web3",
  Data = "Data",
  SWE = "Software Engineer",
  Cybersecurity = "Cybersecurity",
  DataTechnology = "Data",
  Cloud = "Public & Private Cloud",
  Systems = "Systems Engineering",
  WordPress = "WordPress",
  Technical_Writing = "Technical Writing",
}
